title: Sebastien Decuyper
email: s.decuyper314@gmail.com
description: >- 
  Sebastien Decuyper's personal website and blog ! Come say hi, I have games and code stuff.
url: "sebdec.net" # the base hostname & protocol for your site, e.g. http://example.com



# Build settings
theme: minima
plugins:
  - jekyll-feed

